# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          channel: stable
      - run: flutter --version
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test --coverage
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage/lcov.info
          slug: jagaller2000/flutter-avkeypad
          token: ${{ secrets.CODECOV_TOKEN }}
